export interface ChannelCategory {
  name: string;
  image: string;
  sublist: string[];
}

export const channelsData: ChannelCategory[] = [
  { 
    name: 'VIP | PPV-SPORT EVENTS', 
    image: 'https://d3ciwvs59ifrt8.cloudfront.net/374a5424-e68e-45ec-bc44-501a05c0a77c/c716fe41-c0f4-4c58-96ba-b980be362994.png', 
    sublist: [
      "FI-UFC| UFC 1",
      "FI-UFC| UFC 2",
      "FI-UFC| UFC 3",
      "FI-UFC| UFC FIGHT NIGHT 1",
      "FI-UFC| UFC FIGHT NIGHT 2",
      "FI-UFC| UFC FIGHT NIGHT 3",
      "FI-UFC| UFC ON ESPN 1",
      "FI-UFC| UFC ON ESPN 2",
      "FI-UFC| UFC ON FOX 1",
      "FI-WWE| WWE FRIDAY NIGHT SMACKDOWN 1",
      "FI-WWE| WWE FRIDAY NIGHT SMACKDOWN 2",
      "FI-WWE| WWE MAIN EVENT 1",
      "FI-WWE| WWE MONDAY NIGHT RAW 1",
      "FI-WWE| WWE MONDAY NIGHT RAW 2",
      "FI-WWE| WWE NXT UK 1",
      "PPV| NZUK| MMA JUNKIE HD",
      "PPV| UFC 00 ",
      "PPV| UFC 01 ",
      "PPV| UFC 02 ",
      "PPV| UFC 03 ",
      "PPV| UFC 04 ",
      "PPV| UFC 05 ",
      "PPV| UFC 06 ",
      "PPV| UFC 07 ",
      "PPV| UFC 08 ",
      "PPV| UFC 09 ",
      "PPV| UFC 10 ",
      "PPV| GLORY KICKBOXING HD",
      "PPV| GLORY KICKBOXING FHD",
      "PPV| LIVE EVENTS UFC",
      "PPV| LIVE EVENT 01",
      "PPV| LIVE EVENT 02",
      "PPV| LIVE EVENT 03",
      "PPV| LIVE EVENT 04",
      "PPV| LIVE EVENT 05",
      "PPV| LIVE EVENT 06",
      "PPV| LIVE EVENT 07",
      "PPV| LIVE EVENT 08",
      "PPV| LIVE EVENT 09",
      "PPV| LIVE EVENT 10",
      "PPV| LIVE EVENT 11",
      "PPV| LIVE EVENT 12",
      "PPV| LIVE EVENT 13",
      "PPV| LIVE EVENT 14",
      "PPV| LIVE EVENT 15",
      "PPV| LIVE EVENT 16",
      "PPV| LIVE EVENT 17",
      "PPV| LIVE EVENT 18",
      "PPV| LIVE EVENT 19",
      "PPV| LIVE EVENT 20",
      "PPV| LIVE EVENT 21",
      "PPV| LIVE EVENT 22",
      "PPV| LIVE EVENT 23",
      "PPV| LIVE EVENT 24",
      "PPV| LIVE EVENT 25",
      "PPV| LIVE EVENTS 26",
      "PPV| LIVE EVENTS 27",
      "PPV| LIVE EVENTS 28",
      "PPV| LIVE EVENTS 29",
      "PPV| LIVE EVENTS 30",
      "PPV| LIVE EVENTS 31",
      "PPV| LIVE EVENTS 32",
      "PPV| LIVE EVENTS 33",
      "PPV| LIVE EVENTS 34",
      "PPV| UEFA 01",
      "PPV| UEFA 02",
      "PPV| UEFA 03",
      "PPV| UEFA 04",
      "PPV| UEFA 05",
      "PPV| UEFA 06",
      "PPV| UEFA 07",
      "PPV| UEFA 08",
      "PPV| UEFA 09",
      "PPV| UEFA 10",
      "PPV| UEFA 11",
      "PPV| UEFA 12",
      "PPV| UEFA 13",
      "PPV| UEFA 14",
      "PPV| UEFA 15",
      "PPV| UEFA 16",
      "PPV| UEFA 17",
      "PPV| UEFA 18",
      "PPV| UEFA 19",
      "PPV| UEFA 20",
      "PPV| UEFA 21",
      "PPV| UEFA 22",
      "PPV| UEFA 23",
      "PPV| UEFA 24",
      "PPV| UEFA 25",
      "PPV| UEFA 26",
      "PPV| UEFA 27",
      "PPV| UEFA 28",
      "PPV| UEFA 29",
      "PPV| UEFA 30",
      "PPV| UEFA 31",
      "PPV| UEFA 32",
      "PPV| FA PLAYER 01",
      "PPV| FA PLAYER 02",
      "PPV| FA PLAYER 03",
      "PPV| FA PLAYER 04",
      "PPV| FA PLAYER 05",
      "PPV| FA PLAYER 06",
      "PPV| FA PLAYER 07",
      "PPV| FA PLAYER 08",
      "PPV| FA PLAYER 09",
      "PPV| FA PLAYER 10",
      "PPV| FA PLAYER 11",
      "PPV| FA PLAYER 12",
      "PPV| FA PLAYER 13",
      "PPV| FA PLAYER 14",
      "PPV| FA PLAYER 15",
      "PPV| FA PLAYER 16",
      "PPV| FA PLAYER 17",
      "PPV| FA PLAYER 18",
      "PPV| FA PLAYER 19 ",
      "PPV| FA PLAYER 20 ",
      "PPV| FA PLAYER 21 ",
      "PPV| NEW-ZELAND SKY SPORT 1",
      "PPV| NEW-ZELAND SKY SPORT 2",
      "PPV| NEW-ZELAND SKY SPORT 3",
      "PPV| NEW-ZELAND SKY SPORT 4",
      "PPV| NEW-ZELAND SKY SPORT 5",
      "PPV| NEW-ZELAND SKY SPORT 6",
      "PPV| NEW-ZELAND SKY SPORT 7",
      "PPV| NEW-ZELAND SKY SPORT 8",
      "PPV| NEW-ZELAND SKY SPORT 9",
      "PPV| MATCHROOM EVENTS 00",
      "PPV| MATCHROOM EVENTS 01",
      "PPV| MATCHROOM EVENTS 02",
      "PPV| MATCHROOM EVENTS 03",
      "PPV| MATCHROOM EVENTS 04 ",
      "PPV| MATCHROOM EVENTS 05",
      "PPV| MATCHROOM EVENTS 06",
      "PPV| MATCHROOM EVENTS 07",
      "PPV| MATCHROOM EVENTS 08",
      "PPV| MATCHROOM EVENTS 09",
      "PPV| MATCHROOM EVENTS 10",
      "PPV| MATCHROOM EVENTS 11",
      "PPV| MATCHROOM EVENTS 12",
      "PPV| MATCHROOM EVENTS 13",
      "PPV| MATCHROOM EVENTS 14",
      "PPV| MATCHROOM EVENTS 15",
      "PPV| SETANTA EVENT 1 ",
      "PPV| SETANTA EVENT 2 ",
      "PPV| SETANTA EVENT 3 ",
      "PPV| SETANTA EVENT 4 ",
      "PPV| SETANTA EVENT 5 ",
      "PPV| SETANTA EVENT 6 ",
      "PPV| SETANTA EVENT 7 ",
      "PPV| SETANTA EVENT 8 ",
      "PPV| SETANTA EVENT 9 ",
      "PPV| SETANTA EVENT 10",
      "PPV| SETANTA EVENT 11",
      "PPV| SETANTA EVENT 12",
      "PPV| SETANTA EVENT 13",
      "PPV| SETANTA EVENT 14",
      "PPV| SETANTA EVENT 15",
      "PPV| SETANTA EVENT 16",
      "PPV| SETANTA EVENT 17",
      "PPV| SETANTA EVENT 18 ",
      "PPV| SETANTA EVENT 19",
      "PPV| SETANTA EVENT 20",
      "PPV| SETANTA EVENT 21",
      "PPV| SETANTA EVENT 22",
      "PPV| SETANTA EVENT 23",
      "PPV| SETANTA EVENT 24",
      "PPV| SETANTA EVENT 25",
      "PPV| SETANTA EVENT 26",
      "PPV| SETANTA EVENT 27",
      "PPV| SETANTA EVENT 28",
      "PPV| SETANTA EVENT 29",
      "PPV| SETANTA EVENT 30",
      "PPV| WRC 01 ",
      "PPV| WRC 02 ",
      "PPV| WRC 03 ",
      "PPV| WRC 04 ",
      "PPV| MOLA EVENT 1 ",
      "PPV| MOLA EVENT 2 ",
      "PPV| MOLA EVENT 3 ",
      "PPV| MOLA EVENT 4 ",
      "PPV| MOLA EVENT 5 ",
      "PPV| MOLA EVENT 6  ",
      "PPV| MOLA EVENT 7 ",
      "PPV| MOLA EVENT 8 ",
      "PPV| MOLA EVENT 9 ",
      "PPV| MOLA EVENT 10",
      "PPV| MOLA EVENT 11",
      "PPV| MOLA EVENT 12",
      "PPV| MOLA EVENT 13",
      "PPV| PEACOCK ",
      "PPV| PEACOCK ",
      "PPV| PEACOCK ",
      "PPV| PEACOCK ",
      "PPV| PEACOCK ",
      "PPV| PEACOCK 01",
      "PPV| PEACOCK 02 ",
      "PPV| PEACOCK 03",
      "PPV| PEACOCK 04",
      "PPV| PEACOCK 05",
      "PPV| PEACOCK 06",
      "PPV| PEACOCK 07",
      "PPV| PEACOCK 08",
      "PPV| PEACOCK 09",
      "PPV| PEACOCK 10",
      "PPV| PEACOCK 11 ",
      "PPV| EUROSPORT XTRA 1 FHD",
      "PPV| EUROSPORT XTRA 2 FHD",
      "PPV| EUROSPORT XTRA 3 FHD",
      "PPV| EUROSPORT XTRA 4 FHD",
      "PPV| EUROSPORT XTRA 5 FHD",
      "PPV| EUROSPORT XTRA 6 FHD",
      "PPV| EUROSPORT XTRA 7 FHD",
      "PPV| EUROSPORT XTRA 8 FHD",
      "PPV| EUROSPORT XTRA 9 FHD",
      "PPV| EUROSPORT XTRA 10 FHD",
      "PPV| NI PREMIERSHIP FIXTURES 00 ",
      "PPV| NI PREMIERSHIP FIXTURES 01 ",
      "PPV| NI PREMIERSHIP FIXTURES 02 ",
      "PPV| NI PREMIERSHIP FIXTURES 03 ",
      "PPV| NI PREMIERSHIP FIXTURES 04 ",
      "PPV| NI PREMIERSHIP FIXTURES 05 ",
      "PPV| NI PREMIERSHIP FIXTURES 06 ",
      "PPV| NI PREMIERSHIP FIXTURES 07 ",
      "PPV| NI PREMIERSHIP FIXTURES 08 ",
      "PPV| NI PREMIERSHIP FIXTURES 09 ",
      "PPV| HUB PREMIER 1 FHD",
      "PPV| HUB PREMIER 2 FHD",
      "PPV| HUB PREMIER 3 FHD",
      "PPV| HUB PREMIER 4 FHD",
      "PPV| HUB PREMIER 5 FHD",
      "PPV| HUB PREMIER 6 FHD",
      "PPV| HUB PREMIER 7 FHD",
      "PPV| HUB PREMIER 8 FHD",
      "PPV| HUB PREMIER 9 FHD",
      "PPV| HUB PREMIER 10 FHD",
      "PPV| HUB PREMIER 11 FHD",
      "PPV| MOTOGP: MAIN RACE",
      "PPV| MOTOGP: HELI CAM",
      "PPV| MOTOGP: HEADCAM 1",
      "PPV| MOTOGP: HEADCAM 2",
      "PPV| MOTOGP: HEADCAM 3",
      "PPV| MOTOGP: HEADCAM 4",
      "PPV| F1 DATA",
      "PPV| F1-TV",
      "PPV| F1 TRACKER",
      "PPV| F1-HAM-HAMILTON-MERCEDES",
      "PPV| F1-RUS-RUSSELL-MERCEDES",
      "PPV| F1-BOT-BOTTAS-ALFA ROMEO",
      "PPV| F1-ZHO-ZHOU-ALFAROMEO",
      "PPV| F1-VER-VERSTAPPEN-REDBULLRACING",
      "PPV| F1-PER-PEREZ-REDBULLRACING",
      "PPV| F1-LEC-LECLERC-FERRARI",
      "PPV| F1-SAI-SAINZ-FERRARI",
      "PPV| F1-NOR-NORRIS-MCLAREN",
      "PPV| F1-PIA-PIASTRY-MCLAREN",
      "PPV| F1-ALB-ALBON-WILLIAMS",
      "PPV| F1-SAR-SARGEANT-WILLIAMS",
      "PPV| F1-ALO-ALONSO-ALPINE MARTIN",
      "PPV| F1-OCO-OCON-ALPINE",
      "PPV| F1-STR-STROLL-ASTONMARTIN",
      "PPV| F1-HULK-HULKENBURG-HAASF1TEAM",
      "PPV| F1-GAS-GASLY-ALPINE",
      "PPV| F1-TSU-TSUNODA-ALPHATAURI",
      "PPV| F1-DEV-DE VRIES-ALPHATAURI",
      "PPV| F1-MAG-MAGNUSSEN-HAASF1TEAM",
      "PPV| POKER 01 ",
      "PPV| POKER 02 ",
      "PPV| POKER 03 ",
      "PPV| POKER 04 ",
      "PPV| POKER 05:",
      "PPV| TUDN EXTRA 1",
      "PPV| TUDN EXTRA 2",
      "PPV| TUDN EXTRA 3",
      "PPV| TUDN EXTRA 4",
      "PPV| TUDN EXTRA 5",
      "PPV| TUDN EXTRA 6",
      "PPV| TUDN EXTRA 7",
      "PPV| TUDN EXTRA 8",
      "PPV| TUDN EXTRA 9",
      "PPV| TUDN EXTRA 10",
      "PPV| TUDN EXTRA 11",
      "PPV| TENNIS TV 01",
      "PPV| TENNIS TV 02",
      "PPV| TENNIS TV 03",
      "PPV| TENNIS TV 04",
      "PPV| TENNIS TV 05",
      "PPV| TENNIS TV 06",
      "PPV| TENNIS TV 07",
      "PPV| TENNIS TV 08",
      "PPV| TENNIS TV 09",
      "PPV| TENNIS TV 10",
      "PPV| SBO 1 ",
      "PPV| SBO 2 ",
      "PPV| SBO 3 ",
      "PPV| SBO 4 ",
    ] 
  },
  { 
    name: 'AM | CANADA GENERAL', 
    image: 'https://flagicons.lipis.dev/flags/4x3/ca.svg', 
    sublist: [
      "CA| CP24 NEWS HD", 
      "CA| CPAC HD", 
      "CA| CNN HD", 
      "CA| CBC NEWS NETWORK HD", 
      "CA| CTV NEWS CHANNEL HD", 
      "CA| CTV TORONTO HD", 
      "CA| FOX NEWS NETWORK HD", 
      "CA| FOX BUSINESS NETWORK HD", 
      "CA| CNN INTERNATIONAL HD", 
      "CA| W NETWORK HD", 
      "CA| GSN HD", 
      "CA| CNBC HD", 
      "CA| BNN BLOOMBERG HD", 
      "CA| AL JAZEERA ENGLISH HD", 
      "CA| BBC EARTH", 
      "CA| BBC TORONTO GAUNDA PUNJAB", 
      "CA| BBC WORLD HD", 
      "CA| EURONEWS HD", 
      "CA| PBS 9 (KCTS) SEATTLE", 
      "CA| CITY TORONTO HD", 
      "CA| HEADLINE NEWS HD", 
      "CA| MSNBC HD", 
      "CA| THE NEWS FORUM HD", 
      "CA| OMNI 1 HD", 
      "CA| OMNI 2 HD", 
      "CA| OMNI BC HD", 
      "CA| RT NEWS HD", 
      "CA| THE WEATHER NETWORK 2 HD", 
      "CA| THE WEATHER NETWORK HD", 
      "CA| CITY NEWS TORONTO ON HD", 
      "CA| CHCO-TV 26.1 ST. ANDREWS NB HD", 
      "CA| ONTARIO LEGISLATURE HD", 
      "CA| LEGISLATIVE ASSEMBLY OF NEW BRUNSWICK", 
      "CA| ROGERS TV GREY COUNTY HD", 
      "CA| ROGERS TV", 
      "CA| BRAVO HD", 
      "CA| YES TV HD", 
      "CA| QVTV", 
      "CA| BIG TEN HD", 
      "CA| GUSTO", 
      "CA| MAV TV FHD", 
      "CA| W NETWORK WEST HD", 
      "CA| AQUARIUM", 
      "CA| OLN HD", 
      "CA| ETERNAL WORD TELEVISION NETWORK", 
      "CA| TSC HD", 
      "CA| SCREEN SAVER", 
      "CA| FAITH TV HD", 
      "CA| SALT HD", 
      "CA| EWTN HD", 
      "CA| VISION HD", 
      "CA| DAYSTAR TV HD", 
      "CA| (CAM) ST. PHILIPS | NEWFOUNDLAND HD", 
      "CA| (CAM) CORNER BROOK | NEWFOUNDLAND HD", 
      "CA| (CAM) QUIDI VIDI GUT | ST JOHN'S HD", 
      "CA| (CAM) GEORGE STREET | ST JOHN'S HD", 
      "CA| (CAM) LOGY BAY ROAD | ST JOHN'S HD", 
      "CA| (CAM) DOWNTOWN | ST JOHN'S HD", 
      "CA| (CAM) QUIDI VIDI LAKE | ST JOHN'S HD"
    ] 
  },
  { 
    name: 'AM | CANADA FRANÇAIS', 
    image: 'https://flagicons.lipis.dev/flags/4x3/ca.svg', 
    sublist: [
      "CA| (FR) AMITV HD", 
      "CA| (FR) AMI AUDIO HD", 
      "CA| (FR) CANAL S HD", 
      "CA| (FR) ICI RADIO-CANADA TELE TORONTO HD", 
      "CA| (FR) ZTÉLÉ HD", 
      "CA| (FR) VISION HD", 
      "CA| (FR) RDS SPORTS", 
      "CA| (FR) NOOVO CFTF", 
      "CA| (FR) NOOVO ABITIBI-TÉMISCAMINGUE (CFVS-TV)", 
      "CA| (FR) CANAL SAVOIR SD", 
      "CA| (FR) CPAC FRENCH", 
      "CA| (FR) CPAC LIVE EVENT 2", 
      "CA| (FR) CPAC LIVE EVENT 4", 
      "CA| (FR) CPAC LIVE EVENT 6", 
      "CA| (FR) L'ASSEMBLEE NATIONALE DU QUEBEC HD", 
      "CA| (FR) EMCI TV HD", 
      "CA| (FR) EURONEWS HD", 
      "CA| (FR) TVA HULL HD", 
      "CA| (FR) TVA QUEBEC CITY HD", 
      "CA| (FR) TV5 HD", 
      "CA| (FR) METEO MEDIA MONTREAL HD", 
      "CA| (FR) FRANCE 24 HD", 
      "CA| (FR) ICI ARTV HD", 
      "CA| (FR) ICI TELE ACADIE HD", 
      "CA| (FR) ICI TELE ALBERTA HD", 
      "CA| (FR) ICI TELE CB-YUKON HD", 
      "CA| (FR) ICI TELE EST-QUEBEC HD", 
      "CA| (FR) ICI TELE MONTREAL HD", 
      "CA| (FR) ICI TELE QUEBEC HD", 
      "CA| (FR) ICI TELE ONTARIO HD", 
      "CA| (FR) ICI TELE MONCTON FHD", 
      "CA| (FR) ICI TELE VANCOUVER HD", 
      "CA| (FR) ICI TELE MANITOBA HD", 
      "CA| (FR) ICI TELE MAURICIE HD", 
      "CA| (FR) ICI TELE OTTAWA-GATINEAU HD", 
      "CA| (FR) ICI TELE SAGUENAY HD", 
      "CA| (FR) ICI TELE SASKATCHEWAN HD", 
      "CA| (FR) WEATHER NETWORK MONTREAL HD", 
      "CA| (FR) METEO MEDIA HD", 
      "CA| (FR) AFRICA TV HD", 
      "CA| (FR) TELE QUEBEC HD", 
      "CA| (FR) TELEMAGINO HD", 
      "CA| (FR) TELETOON HD", 
      "CA| (FR) DISNEY LA CHAINE HD", 
      "CA| (FR) ICI RADIO CANADA TELE MONCTON HD", 
      "CA| (FR) ICI RADIO-CANADA TELE MONTREAL HD", 
      "CA| (FR) YOOPA HD", 
      "CA| (FR) TFO HD",
      "CA| (FR) LCN HD", 
      "CA| (FR) LCN SD", 
      "CA| (FR) LCN HD [BACK-UP]", 
      "CA| (FR) TVA MONTREAL HD", 
      "CA| (FR) TVA MONTREAL HD [BACK-UP]", 
      "CA| (FR) ICI RDI HD", 
      "CA| (FR) ICI TELE HD",
      "CA| (FR) ELLE HD", 
      "CA| (FR) ADDIK TV HD", 
      "CA| (FR) PRISE HD", 
      "CA| (FR) PRISE2 HD", 
      "CA| (FR) SUPER ECRAN 1 HD", 
      "CA| (FR) SUPER ECRAN 2 HD", 
      "CA| (FR) SUPER ECRAN 3 HD", 
      "CA| (FR) SUPER ECRAN 4 HD", 
      "CA| (FR) SERIES+ HD", 
      "CA| (FR) CINE POP HD", 
      "CA| (FR) NOOVO MONTREAL HD (CFJP TV)", 
      "CA| (FR) NOOVO QUEBEC CITY (CFAP-TV) HD", 
      "CA| (FR) NOOVO SHERBROOKE HD (CFKS-TV)", 
      "CA| (FR) NOOVO TROIS-RIVIERES (CFKM-TV) HD", 
      "CA| (FR) VRAK HD", 
      "CA| (FR) NOOVO HD", 
      "CA| (FR) AMI-TELE HD", 
      "CA| (FR) VU! TELE A LA CARTE PPV", 
      "CA| (FR) A LA CARTE 1 HD", 
      "CA| (FR) A LA CARTE 2 HD", 
      "CA| (FR) A LA CARTE 3 HD", 
      "CA| (FR) A LA CARTE 4 HD", 
      "CA| (FR) A LA CARTE 5 HD", 
      "CA| (FR) A LA CARTE 6 HD", 
      "CA| (FR) A LA CARTE 7 HD", 
      "CA| (FR) A LA CARTE 8 HD", 
      "CA| (FR) A LA CARTE 9 HD", 
      "CA| (FR) A LA CARTE 10 HD",
      "CA| (FR) CASA HD", 
      "CA| (FR) MAX HD", 
      "CA| (FR) EVASION HD", 
      "CA| (FR) FEU DE FOYER HD", 
      "CA| (FR) FRISSONS TV HD", 
      "CA| (FR) TVA TROIS-RIVIERES HD", 
      "CA| (FR) TVA CARLETON HD", 
      "CA| (FR) TVA RIVIERE-DU-LOUP HD", 
      "CA| (FR) CGTN FRANÇAIS HD", 
      "CA| (FR) ICI TELEVISION HD", 
      "CA| (FR) TV ROGERS OTTAWA", 
      "CA| (FR) APTN HD",
      "CA| (FR) MEZZO LIVE HD", 
      "CA| (FR) STINGRAY SPECIAL FRENCH HD", 
      "CA| (FR) STINGRAY NO FENCES HD", 
      "CA| (FR) STINGRAY FRANCO RETRO HD", 
      "CA| (FR) STINGRAY FRANCO COUNTRY HD", 
      "CA| (FR) STINGRAY CLASSICA HD", 
      "CA| (FR) STINGRAY HITS! FHD", 
      "CA| (FR) TRACE AFRICA HD", 
      "CA| (FR) TRACE URBAN AFRIQUE", 
      "CA| (FR) TRACE NAIJA HD", 
      "CA| (FR) TRACE TOCA HD", 
      "CA| (FR) TRACE URBAN HD"
    ] 
  }
];