import appleTvPlusLogo from '../assets/Channels/apple-tv-plus-logo.webp';
import beinSportLogo from '../assets/Channels/bein-sport-logo.webp';
import directTv from '../assets/Channels/direct-tv.webp';
import disneyLogo from '../assets/Channels/disney-logo.webp';
import espnLogo from '../assets/Channels/espn-logo.webp';
import foxLogo from '../assets/Channels/FOX.webp';
import fuboTv from '../assets/Channels/FuboTV.webp';
import fuboTvLogo from '../assets/Channels/fubo-tv-logo.webp';
import golfLogo from '../assets/Channels/golf-logo.webp';
import hboMaxLogoWhite from '../assets/Channels/hbo-max-logo-white.webp';
import huluLogo from '../assets/Channels/hulu-logo.webp';
import leagueBaseballLogo from '../assets/Channels/League_Baseball_logo.webp';
import nbaLogo from '../assets/Channels/nba-logo.webp';
import netflix from '../assets/Channels/netflix.webp';
import nflLogo from '../assets/Channels/nfl-logo.webp';
import nhlLogo from '../assets/Channels/NHL_Logo.webp';
import peacockLogo from '../assets/Channels/peacock-logo.webp';
import ppvLive from '../assets/Channels/PPV-Live.webp';
import premierLeagueLogo from '../assets/Channels/premier-league-logo.webp';
import primeVideoLogo from '../assets/Channels/prime-video-logo.webp';
import showtimeLogo from '../assets/Channels/Showtime-lo.webp';
import skySports from '../assets/Channels/sky-sports.webp';
import tsnLogo from '../assets/Channels/TSN_Logo.webp';

// Create a mapping of channel identifiers to logos
const channelLogos: Record<string, string> = {
  'apple': appleTvPlusLogo,
  'appletv': appleTvPlusLogo,
  'bein': beinSportLogo,
  'direct': directTv,
  'directtv': directTv,
  'disney': disneyLogo,
  'espn': espnLogo,
  'fox': foxLogo,
  'fubo': fuboTv,
  'fubotv': fuboTvLogo,
  'golf': golfLogo,
  'hbo': hboMaxLogoWhite,
  'hulu': huluLogo,
  'league': leagueBaseballLogo,
  'mlb': leagueBaseballLogo,
  'nba': nbaLogo,
  'netflix': netflix,
  'nfl': nflLogo,
  'nhl': nhlLogo,
  'peacock': peacockLogo,
  'ppv': ppvLive,
  'premier': premierLeagueLogo,
  'prime': primeVideoLogo,
  'showtime': showtimeLogo,
  'skysports': skySports,
  'sky': skySports,
  'tsn': tsnLogo,
  'ufc': ppvLive,
  'wwe': ppvLive,
  'fight': ppvLive,
  'motogp': ppvLive,
  'f1': ppvLive,
  'tennis': espnLogo,
  'gaming': espnLogo,
  'esports': espnLogo,
  'news': foxLogo,
  'sport': espnLogo,
  'movie': hboMaxLogoWhite,
  'cinema': hboMaxLogoWhite,
  'channel': foxLogo,
  'tv': foxLogo,
  'network': foxLogo,
  'broadcast': foxLogo,
  'entertainment': disneyLogo,
  'kids': disneyLogo,
  'family': disneyLogo,
  'documentary': huluLogo,
  'doc': huluLogo,
  'music': hboMaxLogoWhite,
  'mtv': hboMaxLogoWhite,
  'bet': hboMaxLogoWhite,
  'comedy': disneyLogo,
  'cbs': foxLogo,
  'abc': foxLogo,
  'nbc': foxLogo,
  'pbs': foxLogo,
  'cw': foxLogo,
  'tbs': espnLogo,
  'tnt': espnLogo,
  'usa': espnLogo,
  'fx': espnLogo,
  'amc': hboMaxLogoWhite,
  'syfy': hboMaxLogoWhite,
  'trutv': espnLogo,
  'history': huluLogo,
  'natgeo': huluLogo,
  'national': huluLogo,
  'geographic': huluLogo,
  'animal': huluLogo,
  'food': huluLogo,
  'cooking': huluLogo,
  'travel': huluLogo,
  'lifestyle': huluLogo,
  'home': huluLogo,
  'garden': huluLogo,
  'hgtv': huluLogo,
  'diy': huluLogo,
  'e': disneyLogo,
  'lifetime': hboMaxLogoWhite,
  'own': hboMaxLogoWhite,
  'bravo': disneyLogo,
  'oxygen': huluLogo,
  'vh1': hboMaxLogoWhite,
  'cmt': hboMaxLogoWhite,
  'country': hboMaxLogoWhite,
  'game': espnLogo,
  'game show': espnLogo,
  'reelz': hboMaxLogoWhite,
  'axs': hboMaxLogoWhite,
  'sundance': hboMaxLogoWhite,
  'ifc': hboMaxLogoWhite,
  'we': disneyLogo,
  'logo': disneyLogo,
  'pop': hboMaxLogoWhite,
  'fuse': hboMaxLogoWhite,
  'viceland': hboMaxLogoWhite,
  'paramount': hboMaxLogoWhite,
  'cnn': foxLogo,
  'msnbc': foxLogo,
  'cnbc': foxLogo,
  'bbc': foxLogo,
  'aljazeera': foxLogo,
  'bloomberg': foxLogo,
  'weather': foxLogo,
  'headlines': foxLogo,
  'investigation': huluLogo,
  'id': huluLogo,
  'discovery': huluLogo,
  'science': huluLogo,
  'velocity': huluLogo,
  'destination': huluLogo,
  'military': huluLogo,
  'tlc': huluLogo,
  'learning': huluLogo,
  'cartoon': disneyLogo,
  'nickelodeon': disneyLogo,
  'nick': disneyLogo,
  'disneyjr': disneyLogo,
  'junior': disneyLogo,
  'baby': disneyLogo,
  'boomerang': disneyLogo,
  'toon': disneyLogo,
  'pbskids': foxLogo,
  'ytv': disneyLogo,
  'treehouse': disneyLogo,
  'teletoon': disneyLogo,
  'familyjr': disneyLogo,
  'cbc': foxLogo,
  'ctv': foxLogo,
  'global': foxLogo,
  'citytv': foxLogo,
  'chch': foxLogo,
  'omni': foxLogo,
  'tva': foxLogo,
  'icitele': foxLogo,
  'noovo': foxLogo,
  'telequebec': foxLogo,
  'meteo': foxLogo,
  'tsc': foxLogo,
  'vision': foxLogo,
  'ztele': foxLogo,
  'ami': foxLogo,
  'telemagino': foxLogo,
  'yoopa': foxLogo,
  'tfo': foxLogo,
  'lcn': foxLogo,
  'addik': foxLogo,
  'vtrak': foxLogo,
  'seriesplus': foxLogo,
  'supercran': foxLogo,
  'cinepop': foxLogo,
  'max': hboMaxLogoWhite,
  'evasion': foxLogo,
  'frisson': foxLogo,
  'musique': foxLogo,
  'mtvfr': foxLogo,
  'mezzo': foxLogo,
  'stingray': foxLogo,
  'trace': foxLogo,
  'africa': foxLogo,
  'urban': foxLogo,
  'naija': foxLogo,
  'toca': foxLogo,
  'classica': foxLogo,
  'hits': foxLogo,
  'retro': foxLogo,
  'countryfr': foxLogo,
  'rock': foxLogo,
  'jazz': foxLogo,
  'blues': foxLogo,
  'spa': foxLogo,
  'kpop': foxLogo,
  'latin': foxLogo,
  'reggaeton': foxLogo,
  'hiphop': foxLogo,
  'rb': foxLogo,
  'soul': foxLogo,
  'alternative': foxLogo,
  'classic': foxLogo,
  'party': foxLogo,
  'dance': foxLogo,
  'edm': foxLogo,
  'today': foxLogo,
  'kidsstuff': foxLogo,
  'nature': foxLogo,
  'nostalgie': foxLogo,
  'adult': foxLogo,
  'beats': foxLogo,
  'throwback': foxLogo,
  'y2k': foxLogo,
  'youth': foxLogo,
  'tropical': foxLogo,
  'brazuka': foxLogo,
  'afrobeats': foxLogo,
  'gospel': foxLogo,
  'kitoko': foxLogo,
  'latina': foxLogo,
  'mziki': foxLogo,
  'muzika': foxLogo,
  'jama': foxLogo,
  'vanilla': foxLogo,
  'ayiti': foxLogo,
  'tvp': foxLogo,
  'afro': foxLogo,
  'punjabi': foxLogo,
  'tag': foxLogo,
  'colors': foxLogo,
  'sony': foxLogo,
  'zee': foxLogo,
  'default': foxLogo
};

// Export both the individual logos and the mapping
export default channelLogos;

// Also export individual logos for direct import
export {
  appleTvPlusLogo,
  beinSportLogo,
  directTv,
  disneyLogo,
  espnLogo,
  foxLogo,
  fuboTv,
  fuboTvLogo,
  golfLogo,
  hboMaxLogoWhite,
  huluLogo,
  leagueBaseballLogo,
  nbaLogo,
  netflix,
  nflLogo,
  nhlLogo,
  peacockLogo,
  ppvLive,
  premierLeagueLogo,
  primeVideoLogo,
  showtimeLogo,
  skySports,
  tsnLogo
};